"""
Human-readable labels for RDKit MACCS keys (bits 1–167).
Source: RDKit SMARTS definitions + Ertl 2006 annotations.

Usage:
    from maccs_labels import MACCS_LABELS
    label = MACCS_LABELS.get(bit_number, f'Key {bit_number}')
"""

MACCS_LABELS = {
    1: 'Isotope label',          2: 'Heavy atom (Z>103)',        3: 'Ge/As/Se/Sn/Sb/Te/Pb/Bi/Po',
    4: 'Actinide',               5: 'Sc/Ti/Y/Zr/Hf',            6: 'Lanthanide',
    7: 'V/Cr/Mn/Nb/Mo/Tc/Ta/W/Re', 8: 'Heteroatom in 4-ring',   9: 'Fe/Co/Ni/Ru/Rh/Pd/Os/Ir/Pt',
   10: 'Alkaline earth',        11: '4-membered ring',          12: 'Cu/Zn/Ag/Cd/Au/Hg',
   13: 'O-N(-C)-C',             14: 'S-S bond',                 15: 'O-C(-O)-O (carbonate)',
   16: 'Heteroatom in 3-ring',  17: 'C#C (alkyne)',             18: 'B/Al/Ga/In/Tl',
   19: '7-membered ring',       20: 'Silicon (Si)',             21: 'C=C(-Q)-Q',
   22: '3-membered ring',       23: 'N-C(-O)-O (carbamate)',    24: 'N-O bond',
   25: 'N-C(-N)-N (guanidine)', 26: 'C=C in ring',             27: 'Iodine (I)',
   28: 'Q-CH2-Q',               29: 'Phosphorus (P)',           30: 'C(-Q)(-C)(-C)',
   31: 'Heteroatom+halogen',    32: 'C-S-N',                    33: 'N-S bond',
   34: 'CH2=* (exo methylene)', 35: 'Alkali metal',             36: 'S in ring',
   37: 'N-C(=O)-N (urea)',      38: 'N-C(-C)-N (aminal)',       39: 'O-S(=O)-O (sulfonate)',
   40: 'S-O bond',              41: 'C#N (nitrile)',            42: 'Fluorine (F)',
   43: 'NH/OH 1,3-related',     44: 'Unusual heteroatom',       45: 'C=C-N',
   46: 'Bromine (Br)',          47: 'S-*-N',                    48: 'O-Q(-O)-O (phosphate)',
   49: 'Charged atom',          50: 'C=C(-C)-C (tetra-alkene)', 51: 'C-S-O',
   52: 'N-N bond',              53: 'NH/OH 1,5-related',        54: 'NH/OH 1,4-related',
   55: 'O-S-O',                 56: 'O-N(-O)-C (N-oxide)',      57: 'O in ring',
   58: 'Q-S-Q',                 59: 'S non-arom in arom',       60: 'S=O (sulfoxide)',
   61: '*-S(-*)-* (trivalent)', 62: 'Ring fusion bond',         63: 'N=O (nitroso)',
   64: 'Ring-S exocyclic',      65: 'Arom C-N (c:n)',           66: 'Quaternary C',
   67: 'Q-S',                   68: 'Two adjacent NH/OH',       69: 'Q-Q-H',
   70: 'Q-N-Q',                 71: 'N-O (hydroxylamine)',      72: 'O-*-*-O (1,4-diol)',
   73: 'S=* (thiocarbonyl)',    74: 'CH3-*-CH3 (gem-dimethyl)', 75: 'N in non-fused ring',
   76: 'C=C(-*)-* (trisubst.)', 77: 'N-*-N',                   78: 'C=N',
   79: 'N-*-*-N',               80: 'N-*-*-*-N',               81: 'S(-*)-*',
   82: '*-CH2-OH/NH',           83: 'Heteroatom in 6-ring',     84: 'NH2 (primary amine)',
   85: 'N(-C)(-C)-C (tert.N)',  86: 'CH2-Q-CH2',               87: 'Halogen in ring',
   88: 'Sulfur (S)',            89: 'O-*-*-*-O (1,5-diol)',     90: 'NH/OH+CH2 (1,2)',
   91: 'NH/OH+CH2 (1,3)',       92: 'O-C(-N)-C (α-aminocarb.)', 93: 'Q-CH3',
   94: 'Q-N',                   95: 'N-*-*-O (NAAO)',          96: '5-membered ring',
   97: 'N-*-*-*-O (NAAAO)',    98: 'Heteroatom in 7-ring',     99: 'C=C (alkene)',
  100: '*-CH2-N',              101: 'Large ring (>=8)',         102: 'Q-O',
  103: 'Chlorine (Cl)',        104: 'NH/OH+CH2 (1,3)',         105: 'Branching ring atom',
  106: 'Q(-Q)-Q (3 heteroatoms)', 107: 'Halogen on branch',    108: 'CH3-*-*-*-CH2',
  109: '*-CH2-O',              110: 'N-C-O (NCO)',             111: 'N-*-CH2',
  112: 'Branching carbon',     113: 'O non-arom in arom',      114: 'CH3-CH2 (ethyl)',
  115: 'CH3-*-CH2 (propyl)',   116: 'CH3-*-*-CH2 (butyl)',     117: 'N-*-O (NAO)',
  118: '-CH2-CH2- (ethylene)', 119: 'N=* (imine/azo)',         120: 'Polycyclic N in ring',
  121: 'N in ring',            122: '*-N(-*)-* (tert.N any)',   123: 'O-C-O (acetal)',
  124: 'Q-Q bond',             125: 'Polycyclic aromatic',     126: '*-O-* (ether)',
  127: 'Ring-O exocyclic',     128: '*-CH2-*-*-*-CH2',        129: '*-CH2-*-*-CH2',
  130: 'Multiple Q-Q bonds',   131: 'NH or OH (H-donor)',      132: 'O-*-CH2',
  133: 'Ring-N exocyclic',     134: 'Halogen (F/Cl/Br/I)',     135: 'N non-arom in arom',
  136: 'Multiple C=O',         137: 'Heteroatom in ring',      138: 'Multiple Q-CH2',
  139: 'OH (hydroxyl)',        140: '>=4 oxygens',             141: '>=3 methyls',
  142: '>=2 nitrogens',        143: 'Ring-O exo (single)',     144: 'Non-arom+arom fusion',
  145: 'Polycyclic 6-ring',    146: '>=3 oxygens',             147: '-CH2-CH2- (any)',
  148: '*-Q(-*)-* (2+ subs.)', 149: '>=2 methyls',            150: 'Non-fused ring bond',
  151: 'NH (sec/pri N-H)',     152: 'O-C(-C)-C (ether/alc.)',  153: 'Q-CH2-* (het+meth.)',
  154: 'C=O (carbonyl)',       155: 'CH2 not in ring',         156: 'N(-*)-* (N+subs.)',
  157: 'C-O (any)',            158: 'C-N (any)',               159: '>=2 oxygens',
  160: 'CH3 (methyl)',         161: 'N (any nitrogen)',         162: 'Aromatic atom',
  163: '6-membered ring',      164: 'O (any oxygen)',           165: 'Ring atom',
  166: 'Fragments/disconn.',   167: 'Heavy atom >= 1',
}
